### ISSUE TITLE
Wrong number of elements when line ends with the delimiter

### ISSUE THREAD

**Issue by jorgemarsal** [roman-kashitsyn/text-csv#7]
I think there's a small bug when a line ends with the delimiter. E.g. when parsing the line "1,2," it should return 3 elements ("1","2" and ""). Instead it's returning only 2.

If the empty element is in the middle like in the line "1,,2", then it returns 3 elements as it should.

```
#include <iostream>
#include <sstream>
#include "text/csv/rows.hpp"

text::csv::row getRow(const std::string& line) {
    std::istringstream ss(line);
    text::csv::csv_istream is(ss, ',');
    text::csv::row row;
    is >> row;
    return row;
}

int main() {
    auto row1 = getRow("1,2");   std::cout << row1.size() << std::endl;
    auto row2 = getRow("1,2,3"); std::cout << row2.size() << std::endl;
    auto row3 = getRow("1,2,");  std::cout << row3.size() << std::endl; // bug? should be 3?
    auto row4 = getRow("1,,3");  std::cout << row4.size() << std::endl;
}
```

You can try the example with:

```
g++ -std=c++11 -I recordparser/text-csv/include/ /tmp/bug.cpp
```

**Comment by roman-kashitsyn** [comment]
Yep, it's a bug, and I'm going to fix it.

**Comment by roman-kashitsyn** [comment]
The issue is caused by the following condition in the row reading code

``` cpp
while (is && is.has_more_fields())
```

When we're reading the last field, `operator bool()` of the `csv_istream` (defined as `is_.good() && !eof()`) returns `false`, since `eof()` returns `true`.

I've decided to add method `bool good()` (delegating work to the `std::istream::good()`) and rewrite the condition as

``` cpp
while (is.good() && is.has_more_fields())
```

This way it's possible to read the last (empty) row even in presence of an unexpected EOF.

**Comment by jorgemarsal** [comment]
Thanks, works great!
